/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 快照克隆请求参数
type SnapCloneRequestView struct {
	// 链接克隆类型
	CloneType string `json:"clone_type,omitempty"`
	// 克隆卷名称
	Name string `json:"name"`
	// 是否数据校验。
	VerifyEnabled bool `json:"verify_enabled"`
	// IO性能优先级。只能是default或priority
	IoPriority string `json:"io_priority"`
	// Volume的QOS配置
	Qos *QosPropertyView `json:"qos"`
	// 目标存储池uuid
	PoolId string `json:"pool_id"`
}
