/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 存储池详情 返回的响应信息
type PoolDetailResponseView struct {
	// 物理池名字
	FailureDomainName string `json:"failure_domain_name"`
	// 纠删码：数据条带数量
	DataChunkCount int32 `json:"data_chunk_count"`
	// 是否独占物理池
	Exclusivity bool `json:"exclusivity"`
	// 存储池冗余策略
	RedundancyPloy string `json:"redundancy_ploy"`
	// 存储池超分比
	ThinProvisioning int32 `json:"thin_provisioning"`
	// 物理池缓存类型
	FailureDomainCacheType string `json:"failure_domain_cache_type"`
	// 资源的创建时间
	CreateTime float32 `json:"create_time"`
	// 资源的健康状态
	HealthStatus string `json:"health_status"`
	// 裸容量
	RawSize int64 `json:"raw_size"`
	// 是否压缩
	Compression bool `json:"compression"`
	// 资源的运行状态
	RunStatus string `json:"run_status"`
	// 最小副本数
	MinSize int32 `json:"min_size"`
	// 存储池id
	PoolId int32 `json:"pool_id"`
	// 数据量
	DataSize int64 `json:"data_size"`
	// 资源的最后时间
	UpdateTime float32 `json:"update_time"`
	// 副本数
	ReplicateSize int32 `json:"replicate_size"`
	// 资源的名称
	Name string `json:"name"`
	// 是否加密
	Encryption bool `json:"encryption"`
	// 存储池状态
	Status string `json:"status"`
	// 存储池用途
	Application string `json:"application"`
	// 物理池类型
	FailureDomainType string `json:"failure_domain_type"`
	// 存储池安全级别
	SafeLevel string `json:"safe_level"`
	// 资源的ID
	Id string `json:"id"`
	// 纠删码：编码条带数量
	CodingChunkCount int32 `json:"coding_chunk_count"`
	// pg均衡进度
	RebalanceProgress int32 `json:"rebalance_progress"`
	// 有效容量
	Quota int64 `json:"quota"`
	// 物理池uuid
	FailureDomainId string `json:"failure_domain_id"`
	// 资源的非健康状态的原因
	HealthStatusReason string `json:"health_status_reason"`
	// 存储池中未分配给卷和桶的容量
	UnallocatedSize int64 `json:"unallocated_size"`
}
