/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 修改网关关联的客户端信息
type UpdateBlockGatewayClientsRequestView struct {
	// 网关待添加或者移除的客户端列表
	Clients []string `json:"clients"`
	// 更新网关关联的客户端执行的操作，添加或者移除
	Action string `json:"action"`
}
