/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 卷缩容的请求参数
type VolumeShrinkRequestView struct {
	// 卷缩容的大小，单位为Bytes, 最小1GB, 最大512TB
	Size int64 `json:"size,omitempty"`
}
