/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 更新客户端卷设备的请求参数
type ClientUpdateLunsRequestView struct {
	// 客户端待添加或者删除的卷设备列表
	Luns []ClientUpdateLunProperty `json:"luns"`
	// 更新客户端卷的操作，添加或者移除
	Action string `json:"action"`
}
