/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 更新网关的请求参数
type UpdateBlockGatewayRequestView struct {
	// 修改网关的chap用户名(约束：8-64个字符，支持大小写字母数字、下划线、连字符、’@‘、冒号、句点，用户名和密码必须同时存在)
	ChapUsername string `json:"chap_username,omitempty"`
	// 修改网关的chap状态
	IsChap bool `json:"is_chap,omitempty"`
	// 更新网关的新名称
	Name string `json:"name,omitempty"`
	// 修改网关的chap密码(约束:12-16个字符，支持大小写字母、数字、下划线、连字符、‘/’、’@‘)
	ChapPassword string `json:"chap_password,omitempty"`
	// 更新网关的描述信息
	Description string `json:"description,omitempty"`
}
