/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 客户端更新Lun设备参数信息
type ClientUpdateLunProperty struct {
	// 挂载或者卸载卷是否只读
	IsReadonly bool `json:"is_readonly"`
	// 挂载或者卸载的类型
	LunType string `json:"lun_type"`
	// 挂载或者卸载卷的ID
	LunId string `json:"lun_id"`
}
