/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 卷的快照恢复请求参数
type VolumeRecoveryRequestView struct {
	// 卷需要恢复的快照的UUID
	SnapId string `json:"snap_id"`
}
