/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 删除快照请求参数
type DeleteBatchSnapshotRequestView struct {
	// 批量删除快照的uuid列表
	Snaps []string `json:"snaps"`
}
