/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 卷关联的客户端的详情信息
type VolumeRelatedClientsResponseDetail struct {
	// 客户端chap的用户名
	ChapUsername string `json:"chap_username"`
	// 资源的名称
	Name string `json:"name"`
	// 客户端是否开启chap
	IsChap bool `json:"is_chap"`
	// 资源的最后时间
	UpdateTime float32 `json:"update_time"`
	// 资源的ID
	Id string `json:"id"`
	// 客户端的描述
	Description string `json:"description"`
	// 客户端关联的客户端节点数
	NodeNum int32 `json:"node_num"`
	// 资源的创建时间
	CreateTime float32 `json:"create_time"`
	// 卷的ID
	VolumeId string `json:"volume_id"`
	// 卷是否只读
	IsReadonly bool `json:"is_readonly"`
}
