/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 设置卷QOS的请求参数
type SetVolumeQosRequestView struct {
	// Volume的QOS配置
	Qos *QosPropertyView `json:"qos"`
}
