/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Qos详情响应结果
type QosDetailResponseView struct {
	// 写最大IOPS限制
	WriteIopsLimit int64 `json:"write_iops_limit,omitempty"`
	// 资源的创建时间
	CreateTime float32 `json:"create_time"`
	// 资源的ID
	Id string `json:"id"`
	// 读突发IOPS限制
	ReadIopsBurst int64 `json:"read_iops_burst,omitempty"`
	// 资源的最后时间
	UpdateTime float32 `json:"update_time"`
	// 写突发IOPS限制
	WriteIopsBurst int64 `json:"write_iops_burst,omitempty"`
	// 写最大带宽限制
	WriteBpsLimit int64 `json:"write_bps_limit,omitempty"`
	// 资源的名称
	Name string `json:"name"`
	// 突发IOPS限制
	IopsBurst int64 `json:"iops_burst,omitempty"`
	// 读突发带宽限制
	ReadBpsBurst int64 `json:"read_bps_burst,omitempty"`
	// 最大IOPS限制
	IopsLimit int64 `json:"iops_limit,omitempty"`
	// 读最大带宽限制
	ReadBpsLimit int64 `json:"read_bps_limit,omitempty"`
	// 读最大IOPS限制
	ReadIopsLimit int64 `json:"read_iops_limit,omitempty"`
	// 突发带宽限制
	BpsBurst int64 `json:"bps_burst,omitempty"`
	// 最大带宽限制
	BpsLimit int64 `json:"bps_limit,omitempty"`
	// 资源的描述
	Description string `json:"description"`
	// 写突发带宽限制
	WriteBpsBurst int64  `json:"write_bps_burst,omitempty"`
	Message       string `json:"message"`
}
