/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 更新卷的IO性能优先级请求参数
type UpdateVolumeIoPriorityRequestView struct {
	// 更新卷的IO性能优先级
	IoPriority string `json:"io_priority"`
}
