/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 网关节点详情的属性信息
type GatewayNodeProperty struct {
	// 网关节点的ID
	NodeId string `json:"node_id,omitempty"`
	// 网关节点的主机名
	Name string `json:"name,omitempty"`
	// 网关节点所在服务器的网关IP
	GatewayIp string `json:"gateway_ip,omitempty"`
	// 网关节点所在服务器的管理IP
	ManagerIp string `json:"manager_ip,omitempty"`
	// 资源的非健康状态的原因
	HealthStatusReason string `json:"health_status_reason"`
	// 网关节点所属块网关的ID
	IscsiGwId string `json:"iscsi_gw_id,omitempty"`
	// 网关节点所在server的ID
	ServerId string `json:"server_id,omitempty"`
	// 资源的创建时间
	CreateTime float32 `json:"create_time"`
	// 资源的健康状态
	HealthStatus string `json:"health_status"`
}
