/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 批量创建Volume的请求参数
type BatchCreateVolumeRequestView struct {
	// 卷的分配容量即卷大小。单位为Bytes, 最小1GB大小
	VolumeSize int64 `json:"volume_size"`
	// 批量创建块存储卷时，卷的起始编号。最小为1
	StartNo int32 `json:"start_no"`
	// 是否数据校验。
	VerifyEnabled bool `json:"verify_enabled"`
	// IO性能优先级。只能是default或priority
	IoPriority string `json:"io_priority"`
	// Volume的QOS配置
	Qos *QosPropertyView `json:"qos"`
	// 卷所属存储池的uuid
	PoolId string `json:"pool_id"`
	// 卷名称前缀
	Prefix string `json:"prefix"`
	// 批量创建的卷个数
	Count int32 `json:"count"`
}
