/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 更新客户端的描述信息请求参数
type UpdateClientDescRequestView struct {
	// 更新客户端的描述信息
	Description string `json:"description"`
}
