/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 可用网关节点
type AvailGwNodeProperty struct {
	// 网关节点的管理IP
	ManagerIp string `json:"manager_ip,omitempty"`
	// 网关节点的名称
	Name string `json:"name,omitempty"`
	// 网关节点的网关IP
	GatewayIp string `json:"gateway_ip,omitempty"`
	// 网关节点的ID
	ServerId string `json:"server_id,omitempty"`
}
