/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 获取Qos列表 响应结果
type ListQosResponseView struct {
	// 列表返回的起始位置
	Index int32 `json:"index,omitempty"`
	// 请求失败时的原因，正常时为空
	Message string `json:"message"`
	// 请求的返回码，正常时为0，失败时为对应错误码，如02.ff.ff.ffff
	RetCode string `json:"ret_code"`
	// 期望查询个数
	Offset int32 `json:"offset,omitempty"`
	// 资源符合条件的总条目数
	Total int32 `json:"total,omitempty"`
	// Qos列表
	Qoss []QosDetailResponseView `json:"qoss,omitempty"`
	// 当前返回符合条件的的条目数
	Count int32 `json:"count,omitempty"`
}
