/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 登录响应参数
type LoginResponseView struct {
	// 角色列表
	RoleList []AuthRoleResponseView `json:"role_list"`
	// refresh token
	RefreshToken string `json:"refresh_token"`
	// access token
	AccessToken string `json:"access_token"`
	// 用户信息
	UserInfo *AuthUserInfoResponseView `json:"user_info"`
	// token类型
	TokenType string `json:"token_type"`
}
