/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 修改快照名称响应结果
type RenameSnapResponseView struct {
	// 快照的详情
	Detail *SnapResponseView `json:"detail,omitempty"`
	// 响应信息
	Message string `json:"message,omitempty"`
	// 响应码
	RetCode string `json:"ret_code,omitempty"`
}
