/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 授权信息 响应结果
type AuthInfoResponseView struct {
	// 授权模块
	AuthDesc string `json:"auth_desc"`
}
