/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 创建iSCSI网关的请求参数
type CreateIscsiGwRequestView struct {
	// 自定义iSCSI网关的IQN，必须符合IQN格式，可不指定该参数
	Iqn string `json:"iqn,omitempty"`
	// iSCSI网关chap用户名(约束：8-64个字符，支持大小写字母数字、下划线、连字符、’@‘、冒号、句点，用户名和密码必须同时存在)
	ChapUsername string `json:"chap_username,omitempty"`
	// 块网关的类型，iSCSI或者SCSI
	GatewayType string `json:"gateway_type"`
	// 网关的端口信息, 目前不支持自定义，只能配置为3260
	Port int32 `json:"port"`
	// iSCSI网关是否启用chap
	IsChap bool `json:"is_chap"`
	// iSCSI网关名称(约束：1-64个字符，支持小写字母、数字、下划线，只能以字母开头
	Name string `json:"name"`
	// iSCSI网关chap密码(约束:12-16个字符，支持大小写字母、数字、下划线、连字符、‘/’、’@‘)
	ChapPassword string `json:"chap_password,omitempty"`
	// 网关包含的网关节点
	Nodes []GatewayAddNodeProperty `json:"nodes"`
	// iSCSI网关描述信息
	Description string `json:"description,omitempty"`
}
