/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 登录请求参数
type LoginRequestView struct {
	// 密码
	Password string `json:"password"`
	// 用户名
	Name string `json:"name"`
}
