/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 块网关列表的返回参数
type BlockGwListResponseView struct {
	// 请求失败时的原因，正常时为空
	Message string `json:"message"`
	// 请求的返回码，正常时为0，失败时为对应错误码，如02.ff.ff.ffff
	RetCode string `json:"ret_code"`
	// 资源符合条件的总条目数
	Total int32 `json:"total,omitempty"`
	// 查询到的网关列表
	Gateways []BlockGatewayDetailProperty `json:"gateways,omitempty"`
	// 当前返回符合条件的的条目数
	Count int32 `json:"count,omitempty"`
}
