/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 更新卷的数据校验请求参数
type UpdateVolumeVerifyEnableRequestView struct {
	// 更新卷的数据校验
	VerifyEnabled bool `json:"verify_enabled"`
}
