/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 更新客户端的CHAP信息
type UpdateClientChapRequestView struct {
	// 修改客户端的chap密码(约束:12-16个字符，支持大小写字母、数字、下划线、连字符、‘/’、’@‘)
	ChapPassword string `json:"chap_password,omitempty"`
	// 修改客户端的chap用户名(约束：8-64个字符，支持大小写字母数字、下划线、连字符、’@‘、冒号、句点，用户名和密码必须同时存在)
	ChapUsername string `json:"chap_username,omitempty"`
	// 修改客户端的chap状态
	IsChap bool `json:"is_chap"`
}
