/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 客户端详情信息
type ClientDetailProperty struct {
	// 关联的网关数量
	IscsiGwCount int32 `json:"iscsi_gw_count"`
	// 客户端开启CHAP的用户名
	ChapUsername string `json:"chap_username,omitempty"`
	// 客户端的ID
	Id string `json:"id"`
	// 客户端添加的客户端主机列表
	Hosts []string `json:"hosts,omitempty"`
	// 资源的最后时间
	UpdateTime float32 `json:"update_time"`
	// 已关联的卷数量
	LunCount int32 `json:"lun_count"`
	// 客户端是否开启CHAP
	IsChap bool `json:"is_chap,omitempty"`
	// 客户端的名称
	Name string `json:"name"`
	// 客户端开启CHAP的密码
	ChapPassword string `json:"chap_password,omitempty"`
	// 已添加的客户端主机数量
	ClientNodeCount int32 `json:"client_node_count"`
	// 客户端的描述信息
	RunStatus string `json:"run_status"`
	// 资源的创建时间
	CreateTime float32 `json:"create_time"`
	// 客户端的描述信息
	Description string `json:"description"`
}
