/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 批量删除卷的请求参数
type VolumeBatchDeleteRequestView struct {
	// 待删除卷的UUID列表
	VolumeIdList []string `json:"volume_id_list"`
	// 是否强制删除，只能是true或false。默认false
	Force bool `json:"force"`
}
