/*
 * ET-GDS
 *
 * ET-GDS API doc.
 *
 * API version: ET-GDS API 7.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 用户信息
type AuthUserInfoResponseView struct {
	// 用户为默认用户时，记录默认用户名
	DefaultAccount string `json:"default_account"`
	// 资源的ID
	Id string `json:"id"`
	// 资源的最后时间
	UpdateTime float32 `json:"update_time"`
	// 用户邮箱
	Mail string `json:"mail"`
	// 资源的名称
	Name string `json:"name"`
	// 是否需要修改密码
	NeedModifyPwd bool `json:"need_modify_pwd"`
	// 资源的创建时间
	CreateTime float32 `json:"create_time"`
	// 用户状态
	UserStatus string `json:"user_status"`
	// 资源的描述
	Description string `json:"description"`
	// 用户手机号
	PhoneNumber string `json:"phone_number"`
}
